# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Aaron\projects\MadLib\PyMadLib\UI\MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(902, 611)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(580, 10, 31, 31))
        self.toolButton.setObjectName("toolButton")
        self.madlib_editor_btn = QtWidgets.QPushButton(self.centralwidget)
        self.madlib_editor_btn.setGeometry(QtCore.QRect(390, 10, 181, 31))
        self.madlib_editor_btn.setObjectName("madlib_editor_btn")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 601, 511))
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setObjectName("textBrowser")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(620, 11, 256, 551))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_source_file = QtWidgets.QAction(MainWindow)
        self.actionImport_source_file.setObjectName("actionImport_source_file")
        self.actionImport_MadLib_File = QtWidgets.QAction(MainWindow)
        self.actionImport_MadLib_File.setObjectName("actionImport_MadLib_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionImport_source_file)
        self.menuFile.addAction(self.actionImport_MadLib_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.madlib_editor_btn.setText(_translate("MainWindow", "Create new MadLib from text"))
        self.label.setText(_translate("MainWindow", "Drag a file to this window, edit an existing madlib or "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport_source_file.setText(_translate("MainWindow", "Import source file"))
        self.actionImport_MadLib_File.setText(_translate("MainWindow", "Import MadLib File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
