# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Aaron\projects\MadLib\PyMadLib\UI\MadLibEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MadEditor(object):
    def setupUi(self, MadEditor):
        MadEditor.setObjectName("MadEditor")
        MadEditor.setWindowModality(QtCore.Qt.ApplicationModal)
        MadEditor.resize(400, 300)
        MadEditor.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(MadEditor)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textEdit = QtWidgets.QTextEdit(MadEditor)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 361, 221))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(MadEditor)
        self.buttonBox.accepted.connect(MadEditor.accept)
        self.buttonBox.rejected.connect(MadEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(MadEditor)

    def retranslateUi(self, MadEditor):
        _translate = QtCore.QCoreApplication.translate
        MadEditor.setWindowTitle(_translate("MadEditor", "Mad Editor"))
